workspace ‘ZJBTestOne.xcworkspace'
use_frameworks!
platform :ios, ‘8.0’

def shared_pods
    pod 'SnapKit', '~> 3.2.0'
    pod 'Moya', '~> 8.0.5'
    pod 'IBAnimatable', '~> 4.1.0'
end

target 'ZJBTestOne’ do
    project 'ZJBTestOne.xcodeproj'
    shared_pods
end
